// Auto-generated by scripts/generate-build-info.js — do not edit manually
export const BUILD_NUMBER = 115;
export const BUILD_STAMP = '2026-02-25T18:56:47.827Z';
export const BUILD_HASH = '83108be';
export const APP_VERSION = '1.6.4';
