// Auto-generated by scripts/generate-build-info.js — do not edit manually
export const BUILD_NUMBER = 184;
export const BUILD_STAMP = '2026-03-16T09:08:01.394Z';
export const BUILD_HASH = '32dd197';
export const APP_VERSION = '1.6.4';
